package io.github.stevdrey.dokene.recommendation.domain;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Sealed hierarchy representing the untrusted, advisory outcome generated by an AI model.
 * Exhaustive pattern matching ensures every outcome (action or refusal) is explicitly handled.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "outcome")
@JsonSubTypes({
    @JsonSubTypes.Type(value = ActionRecommendation.class, name = "ACTION"),
    @JsonSubTypes.Type(value = NoRecommendation.class, name = "NO_RECOMMENDATION")
})
public sealed interface RecommendationOutcome permits ActionRecommendation, NoRecommendation {
    int MAX_RATIONALE_LENGTH = 500;

    String rationale();

    RecommendationConfidence confidence();
}
