// ABOUTME: The closed set of refusal codes feature 2 maps to problem+json (ADR 0023 §4.4).
// ABOUTME: Codes this slice never raises are declared now so later features add no values.
package io.github.stevdrey.dokene.messaging.domain;

public enum MessagingErrorCode {
    INVALID_INPUT, FORBIDDEN, NOT_FOUND, STALE_VERSION, IDEMPOTENCY_KEY_REUSED, INVALID_TRANSITION,
    CUSTOMER_ARCHIVED, DO_NOT_CONTACT, NO_CONTACT_CONSENT, CONTACT_NOT_OWNED, FOLLOW_UP_INELIGIBLE,
    MESSAGE_ALREADY_OPEN, CONTACT_FREQUENCY_EXCEEDED, TEMPLATE_NOT_MAPPED, BODY_REJECTED,
    OUTBOUND_DISABLED_GLOBALLY, OUTBOUND_DISABLED_FOR_TENANT, INTEGRATION_DISABLED, SEND_ATTEMPTS_EXHAUSTED,
    RATE_LIMITED, PROVIDER_UNAVAILABLE
}
