package io.github.stevdrey.dokene.audit.domain;

public enum AuditEventType {
    AUTHORIZATION_DENIED, MEMBERSHIP_ROLE_CHANGED,
    CUSTOMER_CREATED, CUSTOMER_UPDATED, CUSTOMER_ARCHIVED,
    CUSTOMER_CONSENT_CHANGED, CUSTOMER_DO_NOT_CONTACT_CHANGED,
    PURCHASE_RECORDED, PURCHASE_CORRECTED, PURCHASE_VOIDED,
    TENANT_FOLLOW_UP_POLICY_CHANGED, CUSTOMER_FOLLOW_UP_POLICY_CHANGED,
    FOLLOW_UP_SNOOZED, MANUAL_FOLLOW_UP_RECORDED
}
