package io.github.stevdrey.dokene.audit.domain;

public enum AuditEventType {
    AUTHORIZATION_DENIED, MEMBERSHIP_ROLE_CHANGED,
    MEMBERSHIP_CREATED, MEMBERSHIP_REVOKED,
    CUSTOMER_CREATED, CUSTOMER_UPDATED, CUSTOMER_ARCHIVED,
    CUSTOMER_CONSENT_CHANGED, CUSTOMER_DO_NOT_CONTACT_CHANGED,
    PURCHASE_RECORDED, PURCHASE_CORRECTED, PURCHASE_VOIDED,
    TENANT_FOLLOW_UP_POLICY_CHANGED, CUSTOMER_FOLLOW_UP_POLICY_CHANGED,
    FOLLOW_UP_SNOOZED, MANUAL_FOLLOW_UP_RECORDED, FOLLOW_UP_DISMISSED,
    AI_INVOCATION_OUTCOME,
    MESSAGE_SUBMITTED, MESSAGE_APPROVED, MESSAGE_REJECTED, MESSAGE_CANCELLED,
    MESSAGE_SEND_REQUESTED, MESSAGE_SENT, MESSAGE_SEND_FAILED, MESSAGE_SEND_OUTCOME_UNKNOWN,
    MESSAGE_DELIVERY_UPDATED,
    TEMPLATE_MAPPING_UPDATED, INTEGRATION_UPDATED, OUTBOUND_KILL_SWITCH_CHANGED;

    /** The nine message lifecycle events that carry a {@link AuditMetadata.MessageTransition}. */
    public boolean isMessageTransition() {
        return switch (this) {
            case MESSAGE_SUBMITTED, MESSAGE_APPROVED, MESSAGE_REJECTED, MESSAGE_CANCELLED, MESSAGE_SEND_REQUESTED,
                    MESSAGE_SENT, MESSAGE_SEND_FAILED, MESSAGE_SEND_OUTCOME_UNKNOWN, MESSAGE_DELIVERY_UPDATED -> true;
            default -> false;
        };
    }
}
