package io.github.stevdrey.dokene.audit.domain;

public enum AuditEventType {
    AUTHORIZATION_DENIED, MEMBERSHIP_ROLE_CHANGED,
    CUSTOMER_CREATED, CUSTOMER_UPDATED, CUSTOMER_ARCHIVED,
    CUSTOMER_CONSENT_CHANGED, CUSTOMER_DO_NOT_CONTACT_CHANGED
}
