package io.github.stevdrey.dokene.audit.domain;

public enum AuditDenialReason {
    NO_TENANT_CONTEXT, INACTIVE_MEMBERSHIP, MISSING_ROLE, MISSING_PERMISSION,
    MISSING_RESOURCE_TENANT, CROSS_TENANT_RESOURCE, INSUFFICIENT_PERMISSION, UNSPECIFIED
}
