package io.github.stevdrey.dokene.ai.domain;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Sealed hierarchy representing the untrusted, advisory draft outcome generated by an AI model.
 * Exhaustive pattern matching ensures every draft outcome (valid draft or explicit refusal)
 * is handled safely.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "outcome")
@JsonSubTypes({
    @JsonSubTypes.Type(value = MessageDraft.class, name = "DRAFT"),
    @JsonSubTypes.Type(value = NoDraft.class, name = "NO_DRAFT")
})
public sealed interface DraftOutcome permits MessageDraft, NoDraft {
    int MAX_RATIONALE_LENGTH = 500;

    String rationale();

    RecommendationConfidence confidence();
}
