spring:
  application:
    name: dokene
  datasource:
    url: ${DOKENE_DB_URL}
    username: ${DOKENE_DB_USERNAME}
    password: ${DOKENE_DB_PASSWORD}
    hikari:
      connection-init-sql: SET search_path TO dokene
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: dokene
  flyway:
    enabled: true
    url: ${DOKENE_DB_URL}
    user: ${DOKENE_DB_MIGRATION_USERNAME}
    password: ${DOKENE_DB_MIGRATION_PASSWORD}
    schemas: dokene
    default-schema: dokene
    create-schemas: true
    baseline-on-migrate: false
    validate-on-migrate: true
    clean-disabled: true

server:
  shutdown: graceful

management:
  endpoints:
    enabled-by-default: false

logging:
  level:
    root: INFO
